### PR TITLE
Add 12-bit depth support

### PR DESCRIPTION
**Pull request by rk-exxec**
Hey, 
this library is really useful, but I needed to work with 12-bit videos, so I added a small improvement.

I re-ran the tests and there were no issues!

### CODE REVIEW

**Comment by jankoslavic** [comment]
Dear @rk-exxec thanks for the PR. I have invited @klemengit and @domengorjup to review the changes. For now we support reading of 12-bit data via 16-bit built-in int type. 
What is the motivation behind this PR. Using less storage data?
Can you please add also tests? Maybe also performance check? (so we know the impact:))
Thanks

**Comment by domengorjup** [comment]
This implementation works fine for loading 12-bit MRAW files. The reason we haven't added it to pyMRAW before is that in order to pack the 12-bit values into a 16-bit array, it has to load all of them into RAM, whereas the native 16-bit data type can be easily mapped into [`numpy.memmap`](https://numpy.org/doc/stable/reference/generated/numpy.memmap.html) objects at no memory cost.

For smaller videos on reasonably powerful hardware this wouldn't be an issue, but loading large, high-resolution 12-bit MRAW files would very often result in a `MemoryError`.

We could add this feature for completeness (with a warning about opening large files), although not having to worry about file size and memory has been the main reason behind creating pyMRAW in the first place.

The way we've handled 12-bit files is to always save them in the 16-bit MRAW format. This of course has its drawbacks (namely the 1/3 increase in file size), but HDD space is usually less of a problem than RAM.

**Comment by rk-exxec** [comment]
My reasoning behind the PR is, that some 12-bit support would be better than none. And since 12bit is the default export format, this might be useful. Even more so, seeing that your repository is currently the only python library for reading Photron files.

I understand your point about loading into memory. I added this feature for my own work, where I deal with existing 12bit files <1GB, which fit nicely in RAM.
This could be improved by storing the converted data back in a temporary memory-mapped file. But this also will increase loading time.

One could convert all the 12bit to 16bit via the Photron software, but that might be tedious depending on the number of already existing videos.

If you think it would bee good to go ahead with this PR, I can add the tests, warnings and do some performance testing.

**Comment by jankoslavic** [comment]
I would go on with this, but clear warnings should be added that with regards to comments by @domengorjup

**Comment by rk-exxec** [comment]
Performance test: 
For performance testing, I used the following function and executed it for two identical videos, once saved in 12bit mode and once in 16bit mode.
```py
@pytest.mark.filterwarnings('ignore')
def test_perf_12bit_process():
    import numpy as np
    path_str = "./data/ball_12bit_full.cihx"
    video, info = pyMRAW.load_video(path_str)
    N = info['Total Frame']
    h = info['Image Height']
    w = info['Image Width']
    bit = info['Color Bit']

    streak = np.zeros((N,h), dtype=np.uint16)

    for i in range(N):
        streak[i] = video[i,:,w//2]

    streak = streak.T
```
Results:
|ITEM                   |TOTAL_TIME       |USER_TIME|KERNEL_TIME|CPU_USAGE        |MEM_USAGE   |
|-----------------------|-----------------|---------|-----------|-----------------|------------|
|test_perf_12bit_process|0.408150672912598|0.171875 |0.125      |0.727366190239195|376.70703125|
|test_perf_16bit_process|0.138290405273438|0.015625 |0.015625   |0.225973739379896|14.4375     |

**Review by klemengit — APPROVED** [review]

**Comment by jankoslavic** [comment]
@rk-exxec please give us some more time; we have a huge commitment this week. I ask for understanding.

**Comment by rk-exxec** [comment]
No problem at all. I am using my modified version of the file for my project for now, so there is no rush to publish these changes.

**Review by domengorjup — APPROVED** [review]
Everything seems good, I think we can merge this.

**Comment by jankoslavic** [comment]
Thank you all!

**Pull request merged**
